"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
import environ  #追記
from django.contrib import messages

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 追記 ----
env = environ.Env()
root = environ.Path(BASE_DIR / 'secrets')

# 追記 開発環境 ----
env.read_env(root('.env.dev'))

# 追記 本番環境 ----
#env.read_env(root('.env.prod'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = env.str('SECRET_KEY')
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = env.bool('DEBUG')
DEBUG =  os.environ.get('DEBUG_MODE', 'False') == 'True'

#ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.herokuapp.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # 追記
    'cloudinary_storage', # 追記
    'cloudinary', # 追記
    'base', #作成したアプリケーションを追加
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'config.custom_context_processors.base',  # 追記
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_DATABASE'),
        'USER': os.environ.get('DB_USERNAME'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    },
}

#SECRET_KEY = env.str('SECRET_KEY')
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'        # 変更

TIME_ZONE = 'Asia/Tokyo'    # 変更

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# staticは静的ファイルを管理するフォルダ
STATICFILES_DIRS = [BASE_DIR / 'static']    # 追記
STATIC_ROOT = BASE_DIR / 'staticfiles'   # HEROKUデプロイのため追記

MEDIA_URL = '/media/' # 追記
MEDIA_ROOT = BASE_DIR / 'media_local' # 追記

# 画像の設定 #.envへ移動する
CLOUDINARY_STORAGE  = {
    'CLOUD_NAME': os.environ.get('CLOUD_NAME'),
    'API_KEY': os.environ.get('API_KEY'),
    'API_SECRET': os.environ.get('API_SECRET')
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # HEROKUデプロイ時のみ追加
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage' # HEROKUデプロイ時のみ追加
# DEFAULT_AUTO_FIELD = env.str('DEFAULT_AUTO_FIELD', default=None)
# DEFAULT_FILE_STORAGE = env.str('DEFAULT_FILE_STORAGE', default=None)

# if DEBUG:
#     # ローカル開発用
#     DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#     DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
# else:
#     # Heroku本番用
#     DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#     DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 追加 消費税率
TAX_RATE = 0.1

# 追加 Stripe API Key
#STRIPE_API_SECRET_KEY = env.str('STRIPE_API_SECRET_KEY')
STRIPE_API_SECRET_KEY = os.environ.get('STRIPE_API_SECRET_KEY')

 
# 追加 スキーマ＆ドメイン
# MY_URL = 'http://127.0.0.1:8000/'
MY_URL = os.environ.get('MY_URL')

# カスタムユーザーモデル
AUTH_USER_MODEL = 'base.User'

# ユーザーモデルのログインページ
LOGIN_URL = '/login/'

# ログインした後のリダイレクトページ
LOGIN_REDIRECT_URL = '/'

# ユーザーモデルのログアウトページ
LOGOUT_URL = '/logout/'

# ログアウトした後のリダイレクトページ
LOGOUT_REDIRECT_URL = '/login/'

# massages
MESSAGE_TAGS = { # 指定したtagによってクラスを追加して装飾を分ける
    messages.ERROR: 'rounded-0 alert alert-danger',
    messages.WARNING: 'rounded-0 alert alert-warning',
    messages.SUCCESS: 'rounded-0 alert alert-success',
    messages.INFO: 'rounded-0 alert alert-info',
    messages.DEBUG: 'rounded-0 alert alert-secondary',
}


# custom_context カスタムコンテキスト
TITLE = 'VegeKet'

